name: Release

on: workflow_dispatch

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Release by changesets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js v20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install pnpm v9.x
        run: npm i pnpm@^9 -g

      - name: Install dependencies
        run: pnpm install

      - name: Release by changesets
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: 'release: upgrade packages version by GitHub Action'
          title: 'release: upgrade packages version by GitHub Action'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
