name: Release

on:
  push:
    branches:
      - main

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Release by changesets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js v18.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Install pnpm v9.3.0
        run: npm i pnpm@9.3.0 -g

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm run build

      - name: Release by changesets
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: 'release: update versions by GitHub Actions'
          title: 'release: update versions by GitHub Actions'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}